name: SimpleFactions
version: 0.1.0
main: local.simplefactions.SimpleFactionsPlugin
api-version: "1.21"
commands:
  f:
    description: Factions command
    usage: /f
  help:
    description: Show server plugin command help
    usage: /help [page]
    aliases: [shelp, serverhelp]
